/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Juanito
 */
public class Otros extends javax.swing.JFrame {

    /**
     * Creates new form Otros
     */
    public Otros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        cardPlaylist1 = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        lblImagen12 = new javax.swing.JLabel();
        cardPlaylist2 = new javax.swing.JPanel();
        lblImagen9 = new javax.swing.JLabel();
        lblTitulo3 = new javax.swing.JLabel();
        lblSubtitulo1 = new javax.swing.JLabel();
        cardPlaylist3 = new javax.swing.JPanel();
        lblImagen10 = new javax.swing.JLabel();
        lblTitulo4 = new javax.swing.JLabel();
        lblSubtitulo2 = new javax.swing.JLabel();
        cardPlaylist5 = new javax.swing.JPanel();
        lblImagen11 = new javax.swing.JLabel();
        lblTitulo5 = new javax.swing.JLabel();
        lblSubtitulo3 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        lblImagen15 = new javax.swing.JLabel();
        lblTitulo8 = new javax.swing.JLabel();
        lblSubtitulo6 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        lblImagen14 = new javax.swing.JLabel();
        lblTitulo7 = new javax.swing.JLabel();
        lblSubtitulo5 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        lblImagen16 = new javax.swing.JLabel();
        lblTitulo9 = new javax.swing.JLabel();
        lblSubtitulo7 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        lblImagen13 = new javax.swing.JLabel();
        lblTitulo6 = new javax.swing.JLabel();
        lblSubtitulo4 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cardPlaylist1.setBackground(new java.awt.Color(28, 28, 28));
        cardPlaylist1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        cardPlaylist1.setPreferredSize(new java.awt.Dimension(150, 150));
        cardPlaylist1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo1.setText("MEMENTO");
        cardPlaylist1.add(lblTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 114, -1, -1));

        lblSubtitulo.setForeground(new java.awt.Color(179, 179, 179));
        lblSubtitulo.setText("RE:ZERO");
        cardPlaylist1.add(lblSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 136, -1, -1));
        cardPlaylist1.add(lblImagen12, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, 132, 99));

        jPanel2.add(cardPlaylist1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, 160));

        cardPlaylist2.setBackground(new java.awt.Color(28, 28, 28));
        cardPlaylist2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        cardPlaylist2.setPreferredSize(new java.awt.Dimension(150, 150));
        cardPlaylist2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagen9.setText("jLabel2");
        cardPlaylist2.add(lblImagen9, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, 132, 99));

        lblTitulo3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTitulo3.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo3.setText("lblTitulo");
        cardPlaylist2.add(lblTitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 114, -1, -1));

        lblSubtitulo1.setForeground(new java.awt.Color(179, 179, 179));
        lblSubtitulo1.setText("lblSubtitulo");
        cardPlaylist2.add(lblSubtitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 136, -1, -1));

        jPanel2.add(cardPlaylist2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, 160));

        cardPlaylist3.setBackground(new java.awt.Color(28, 28, 28));
        cardPlaylist3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        cardPlaylist3.setPreferredSize(new java.awt.Dimension(150, 150));
        cardPlaylist3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagen10.setText("jLabel2");
        cardPlaylist3.add(lblImagen10, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, 124, 99));

        lblTitulo4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTitulo4.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo4.setText("lblTitulo");
        cardPlaylist3.add(lblTitulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 114, -1, -1));

        lblSubtitulo2.setForeground(new java.awt.Color(179, 179, 179));
        lblSubtitulo2.setText("lblSubtitulo");
        cardPlaylist3.add(lblSubtitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 136, -1, -1));

        jPanel2.add(cardPlaylist3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, 160));

        cardPlaylist5.setBackground(new java.awt.Color(28, 28, 28));
        cardPlaylist5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        cardPlaylist5.setPreferredSize(new java.awt.Dimension(150, 150));
        cardPlaylist5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagen11.setText("jLabel2");
        cardPlaylist5.add(lblImagen11, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, 124, 99));

        lblTitulo5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTitulo5.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo5.setText("lblTitulo");
        cardPlaylist5.add(lblTitulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 114, -1, -1));

        lblSubtitulo3.setForeground(new java.awt.Color(179, 179, 179));
        lblSubtitulo3.setText("lblSubtitulo");
        cardPlaylist5.add(lblSubtitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 136, -1, -1));

        jPanel2.add(cardPlaylist5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 160));

        jPanel18.setBackground(new java.awt.Color(28, 28, 28));
        jPanel18.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel18.setPreferredSize(new java.awt.Dimension(150, 150));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagen15.setText("jLabel2");
        jPanel18.add(lblImagen15, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, 132, 99));

        lblTitulo8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTitulo8.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo8.setText("lblTitulo");
        jPanel18.add(lblTitulo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 114, -1, -1));

        lblSubtitulo6.setForeground(new java.awt.Color(179, 179, 179));
        lblSubtitulo6.setText("lblSubtitulo");
        jPanel18.add(lblSubtitulo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 136, -1, -1));

        jPanel2.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, 155));

        jPanel17.setBackground(new java.awt.Color(28, 28, 28));
        jPanel17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel17.setPreferredSize(new java.awt.Dimension(150, 150));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagen14.setText("jLabel2");
        jPanel17.add(lblImagen14, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, 132, 99));

        lblTitulo7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTitulo7.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo7.setText("lblTitulo");
        jPanel17.add(lblTitulo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 114, -1, -1));

        lblSubtitulo5.setForeground(new java.awt.Color(179, 179, 179));
        lblSubtitulo5.setText("lblSubtitulo");
        jPanel17.add(lblSubtitulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 136, -1, -1));

        jPanel2.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, 155));

        jPanel19.setBackground(new java.awt.Color(28, 28, 28));
        jPanel19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel19.setPreferredSize(new java.awt.Dimension(150, 150));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagen16.setText("jLabel2");
        jPanel19.add(lblImagen16, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, 132, 99));

        lblTitulo9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTitulo9.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo9.setText("lblTitulo");
        jPanel19.add(lblTitulo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 114, -1, -1));

        lblSubtitulo7.setForeground(new java.awt.Color(179, 179, 179));
        lblSubtitulo7.setText("lblSubtitulo");
        jPanel19.add(lblSubtitulo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 136, -1, -1));

        jPanel2.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, 155));

        jPanel16.setBackground(new java.awt.Color(28, 28, 28));
        jPanel16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel16.setPreferredSize(new java.awt.Dimension(150, 150));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagen13.setText("jLabel2");
        jPanel16.add(lblImagen13, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, 132, 99));

        lblTitulo6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTitulo6.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo6.setText("lblTitulo");
        jPanel16.add(lblTitulo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 114, -1, -1));

        lblSubtitulo4.setForeground(new java.awt.Color(179, 179, 179));
        lblSubtitulo4.setText("lblSubtitulo");
        jPanel16.add(lblSubtitulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 136, -1, -1));

        jPanel2.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 155));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FONDOverde.jpeg"))); // NOI18N
        lblFondo.setText("IMAGEN");
        jPanel2.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 680, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(52, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(35, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardPlaylist1;
    private javax.swing.JPanel cardPlaylist2;
    private javax.swing.JPanel cardPlaylist3;
    private javax.swing.JPanel cardPlaylist5;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblImagen10;
    private javax.swing.JLabel lblImagen11;
    private javax.swing.JLabel lblImagen12;
    private javax.swing.JLabel lblImagen13;
    private javax.swing.JLabel lblImagen14;
    private javax.swing.JLabel lblImagen15;
    private javax.swing.JLabel lblImagen16;
    private javax.swing.JLabel lblImagen9;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblSubtitulo1;
    private javax.swing.JLabel lblSubtitulo2;
    private javax.swing.JLabel lblSubtitulo3;
    private javax.swing.JLabel lblSubtitulo4;
    private javax.swing.JLabel lblSubtitulo5;
    private javax.swing.JLabel lblSubtitulo6;
    private javax.swing.JLabel lblSubtitulo7;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JLabel lblTitulo4;
    private javax.swing.JLabel lblTitulo5;
    private javax.swing.JLabel lblTitulo6;
    private javax.swing.JLabel lblTitulo7;
    private javax.swing.JLabel lblTitulo8;
    private javax.swing.JLabel lblTitulo9;
    // End of variables declaration//GEN-END:variables
}
